# Projeto Final Aplicado a Ciência de Dados
## Deteção de Outliers em Contratos Públicos e Previsão do Montante de Adjudição

## Grupo 08
## Membros:
###          - Afonso Alexandre nº 123425;
###          - André  Freitas nº 123409;
###          - Gonçalo Vilhena nº 123384;
###          - Rodolfo Nardy nº 123419

#### **Reading and checking data**

In [1]:
import pandas as pd

In [2]:
#Diretório onde os arquivos de dados do trabalho estão armazenados
data_dir = "./dados/"
df_2018 = pd.read_excel(data_dir + "contratos2018.xlsx")

## Análise


### Funções auxiliares

#### Função para os top X valores mais frequentes

In [3]:
def print_top_n(df, column_name, top_n=20):
    if column_name not in df.columns:
        print(f"Column '{column_name}' not found in the DataFrame.")
        return

    # Calculate the top 'n' most frequent values
    top_n_values = df[column_name].value_counts().head(top_n)

    # Print the top 'n' values
    print(f"Top {top_n} most frequent values for '{column_name}':")
    print(top_n_values)

#### Função para os top X valores mais frequentes numa lista

In [4]:
def print_top_n_list(df, column_name, top_n=20):
    if column_name not in df.columns:
        print(f"Column '{column_name}' not found in the DataFrame.")
        return

    # Explode the lists into separate rows
    exploded = df[column_name].explode()

    # Calculate the top 'n' most frequent individual values
    top_n_values = exploded.value_counts().head(top_n)

    # Print the results
    print(f"Top {top_n} most frequent values for '{column_name}':")
    print(top_n_values)


#### Função para mostras os X menores valores menos frequentes

In [5]:
def print_bottom_n(df, column_name, bottom_n=20):
    if column_name not in df.columns:
        print(f"Column '{column_name}' not found in the DataFrame.")
        return

    # Calculate value counts and get the bottom 'n' values
    bottom_n_values = df[column_name].value_counts().sort_values(ascending=True).head(bottom_n)

    # Print the bottom 'n' values
    print(f"Bottom {bottom_n} least frequent values for '{column_name}':")

    print(bottom_n_values)

 #### Função para mostrar  X menores valores menos frequentes numa lista

#### Function to count null and empty values

In [6]:
def count_null_and_empty(df, column_name):
    total = len(df)

    # Count NaN (null) values
    null_count = df[column_name].isna().sum()
    null_pct = (null_count / total) * 100

    # Count empty string values (after stripping whitespace)
    empty_count = (df[column_name].astype(str).str.strip() == '').sum()
    empty_pct = (empty_count / total) * 100

    # Print results
    print(f"Null (NaN) values: {null_count} ({null_pct:.2f}%)")
    print(f"Empty string values: {empty_count} ({empty_pct:.2f}%)")

#### Informações gerais do ficheiro

In [7]:
df_2018.info()
df_2018.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127887 entries, 0 to 127886
Data columns (total 35 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   idcontrato                127887 non-null  int64
 1   nAnuncio                  12580 non-null   object
 2   TipoAnuncio               12580 non-null   object
 3   idINCM                    12580 non-null   float64
 4   tipoContrato              127885 non-null  object
 5   idprocedimento            127887 non-null  int64
 6   tipoprocedimento          127887 non-null  object
 7   objectoContrato           127887 non-null  object
 8   descContrato              127879 non-null  object
 9   adjudicante               127887 non-null  object
 10  adjudicatarios            127754 non-null  object
 11  dataPublicacao            127887 non-null  datetime64[ns]
 12  dataCelebracaoContrato    127873 non-null  datetime64[ns]
 13  precoContratual           127887 non-null  float64
 14  CPV                       127886 non-null  object
 15  prazoExecucao             127887 non-null  int64
 16  LocalExecucao             127652 non-null  object
 17  fundamentacao             127871 non-null  object
 18  ProcedimentoCentralizado  127887 non-null  object
 19  numAcordoQuadro           15099 non-null   float64
 20  DescrAcordoQuadro         15099 non-null   object
 21  precoBaseProcedimento     127887 non-null  float64
 22  dataDecisaoAdjudicacao    125021 non-null  datetime64[ns]
 23  dataFechoContrato         49678 non-null   datetime64[ns]
 24  PrecoTotalEfetivo         127887 non-null  float64
 25  regime                    127878 non-null  object
 26  justifNReducEscrContrato  2923 non-null    object
 27  tipoFimContrato           51714 non-null   object
 28  CritMateriais             127887 non-null  object
 29  concorrentes              31594 non-null   object
 30  linkPecasProc             237 non-null     object
 31  Observacoes               13878 non-null   object
 32  ContratEcologico          127887 non-null  object
 33  fundamentAjusteDireto     50823 non-null   object
 34  Ano                       127887 non-null  int64
dtypes: datetime64[ns](4), float64(5), int64(4), object(22)
memory usage: 34.1+ MB

Index(['idcontrato', 'nAnuncio', 'TipoAnuncio', 'idINCM', 'tipoContrato',
       'idprocedimento', 'tipoprocedimento', 'objectoContrato', 'descContrato',
       'adjudicante', 'adjudicatarios', 'dataPublicacao',
       'dataCelebracaoContrato', 'precoContratual', 'CPV', 'prazoExecucao',
       'LocalExecucao', 'fundamentacao', 'ProcedimentoCentralizado',
       'numAcordoQuadro', 'DescrAcordoQuadro', 'precoBaseProcedimento',
       'dataDecisaoAdjudicacao', 'dataFechoContrato', 'PrecoTotalEfetivo',
       'regime', 'justifNReducEscrContrato', 'tipoFimContrato',
       'CritMateriais', 'concorrentes', 'linkPecasProc', 'Observacoes',
       'ContratEcologico', 'fundamentAjusteDireto', 'Ano'],
      dtype='object')

#### idcontrato (int64)

In [8]:
count_null_and_empty(df_2018, 'idcontrato')

Null (NaN) values: 0 (0.00%)
Empty string values: 0 (0.00%)

In [ ]:
#não há repetidos
print_top_n(df_2018,"idcontrato",10)

Top 10 most frequent values for 'idcontrato':
idcontrato
10434426    2
10440412    2
10462403    2
10488874    2
10458084    2
10463818    2
10565267    2
4043540     1
10446896    1
10496192    1
Name: count, dtype: int64

In [12]:
ids_repetidos = df_2018["idcontrato"].value_counts()
ids_repetidos = ids_repetidos[ids_repetidos > 1].index
df_2018[df_2018["idcontrato"].isin(ids_repetidos)].sort_values("idcontrato")

,idcontrato,nAnuncio,TipoAnuncio,idINCM,tipoContrato,idprocedimento,tipoprocedimento,objectoContrato,descContrato,adjudicante,...,regime,justifNReducEscrContrato,tipoFimContrato,CritMateriais,concorrentes,linkPecasProc,Observacoes,ContratEcologico,fundamentAjusteDireto,Ano
94929,10434426,NaN,NaN,NaN,Aquisição de bens móveis,3606901,Ajuste Direto Regime Geral,A presente aquisição é imprescindível para div...,Aquisição de elementos do KIT + Autonomia + Re...,500051070 - Município de Lisboa,...,Código dos Contratos Públicos ( DL 111-B/2017 ),NaN,NaN,Não,NaN,NaN,NaN,Não,ausência de recursos próprios,2018
127808,10434426,NaN,NaN,NaN,Aquisição de bens móveis,3606901,Ajuste Direto Regime Geral,A presente aquisição é imprescindível para div...,Aquisição de elementos do KIT + Autonomia + Re...,500051070 - Município de Lisboa,...,Código dos Contratos Públicos ( DL 111-B/2017 ),NaN,NaN,Não,NaN,NaN,NaN,Sim,ausência de recursos próprios,2018
96591,10440412,NaN,NaN,NaN,Aquisição de bens móveis,3397932,Consulta Prévia,Aquisição de viatura de 9 Lugares Tipo L1 H1,Apresentação de Proposta para aquisição de via...,506931382 - Freguesia de Gaeiras,...,Código dos Contratos Públicos ( DL 111-B/2017 ),NaN,"O cumprimento, a impossibilidade definitiva e ...",Não,500254273-SACEL - SOCIEDADE AUTO CENTRAL LEIRI...,NaN,NaN,Sim,NaN,2018
95011,10440412,NaN,NaN,NaN,Aquisição de bens móveis,3397932,Consulta Prévia,Aquisição de viatura de 9 Lugares Tipo L1 H1,Apresentação de Proposta para aquisição de via...,506931382 - Freguesia de Gaeiras,...,Código dos Contratos Públicos ( DL 111-B/2017 ),NaN,"O cumprimento, a impossibilidade definitiva e ...",Não,500254273-SACEL - SOCIEDADE AUTO CENTRAL LEIRI...,NaN,NaN,Não,NaN,2018
96619,10458084,NaN,NaN,NaN,Aquisição de serviços,3577972,Consulta Prévia,Aquisição de serviço de telecomunicações,Aquisição de serviço de telecomunicações,600076237 - Agrupamento de Escolas Miguel Torg...,...,Código dos Contratos Públicos ( DL 111-B/2017 ),NaN,"O cumprimento, a impossibilidade definitiva e ...",Não,502604751-NOS - Comunicações S.A.\n502544180-V...,NaN,NaN,Sim,NaN,2018
95382,10458084,NaN,NaN,NaN,Aquisição de serviços,3577972,Consulta Prévia,Aquisição de serviço de telecomunicações,Aquisição de serviço de telecomunicações,600076237 - Agrupamento de Escolas Miguel Torg...,...,Código dos Contratos Públicos ( DL 111-B/2017 ),NaN,"O cumprimento, a impossibilidade definitiva e ...",Não,502604751-NOS - Comunicações S.A.\n502544180-V...,NaN,NaN,Não,NaN,2018
95059,10462403,NaN,NaN,NaN,Aquisição de serviços,4426389,Consulta Prévia,Recolha e transporte a destino final de gradad...,Recolha e transporte a destino final de gradad...,508114381 - AS - Empresa das Águas de Santarém...,...,Código dos Contratos Públicos ( DL 111-B/2017 ),NaN,"O cumprimento, a impossibilidade definitiva e ...",Não,"507717562-Eco Impact, S.A.\n502550066-TRIU-TEC...",NaN,NaN,Não,NaN,2018
96628,10462403,NaN,NaN,NaN,Aquisição de serviços,4426389,Consulta Prévia,Recolha e transporte a destino final de gradad...,Recolha e transporte a destino final de gradad...,508114381 - AS - Empresa das Águas de Santarém...,...,Código dos Contratos Públicos ( DL 111-B/2017 ),NaN,"O cumprimento, a impossibilidade definitiva e ...",Não,"507717562-Eco Impact, S.A.\n502550066-TRIU-TEC...",NaN,NaN,Sim,NaN,2018
95385,10463818,NaN,NaN,NaN,Concessão de obras públicas,3672138,Ajuste Direto Regime Geral,Ampliação do Cemitério de Giões (18 gavetões),Ampliação do Cemitério de Giões (18 gavetões),506887049 - Freguesia de Giões,...,Código dos Contratos Públicos ( DL 111-B/2017 ),NaN,"O cumprimento, a impossibilidade definitiva e ...",Não,NaN,NaN,NaN,Não,ausência de recursos próprios,2018
127863,10463818,NaN,NaN,NaN,Concessão de obras públicas,3672138,Ajuste Direto Regime Geral,Ampliação do Cemitério de Giões (18 gavetões),Ampliação do Cemitério de Giões (18 gavetões),506887049 - Freguesia de Giões,...,Código dos Contratos Públicos ( DL 111-B/2017 ),NaN,"O cumprimento, a impossibilidade definitiva e ...",Não,NaN,NaN,NaN,Sim,ausência de recursos próprios,2018
127869,10488874,NaN,NaN,NaN,Aquisição de bens móveis,3581916,Ajuste Direto Regime Geral,Fornecimento Contínuo de Bens de Consumo Alime...,Procedimento por ajuste direto para Fornecimen...,"504748114 - Desmor, E. M., S. A.",...,Código dos Contratos Públicos ( DL 111-B/2017 ),NaN,"O cumprimento, a impossibilidade definitiva e ...",Não,NaN,NaN,NaN,Não,ausência de recursos próprios,2018
95063,10488874,NaN,NaN,NaN,Aquisição de bens móveis,3581916,Ajuste Direto Regime Geral,Fornecimento Contínuo de Bens de Consumo Alime...,Procedimento por ajuste direto para Fornecimen...,"504748114 - Desmor, E. M., S. A.",...,Código dos Contratos Públicos ( DL 111-B/2017 ),NaN,"O cumprimento, a impossibilidade definitiva e ...",Não,NaN,NaN,NaN,Sim,ausência de recursos próprios,2018
95407,10565267,NaN,NaN,NaN,Aquisição de bens móveis,4337505,Consulta Prévia,Aquisição de veículo ligeiro de passageiros de...,Aquisição de Viatura,511101210 - Casa do Povo de Água de Pena,...,Código dos Contratos Públicos (DL 111-B/2017 )...,"Artigo 41.º do DLR n.º 27/2015/A, preço contra...","O cumprimento, a impossibilidade definitiva e ...",Não,"511016263-AUTOZARCO - Comércio de Automóveis, SA",NaN,NaN,Não,NaN,2018
127876,10565267,NaN,NaN,NaN,Aquisição de bens móveis,4337505,Consulta Prévia,Aquisição de veículo ligeiro de passageiros de...,Aquisição de Viatura,511101210 - Casa do Povo de Água de Pena,...,Código dos Contratos Públicos (DL 111-B/2017 )...,"Artigo 41.º do DLR n.º 27/2015/A, preço contra...","O cumprimento, a impossibilidade definitiva e ...",Não,"511016263-AUTOZARCO - Comércio de Automóveis, SA",NaN,NaN,Sim,NaN,2018

#### tipoContrato (object)

In [13]:
count_null_and_empty(df_2018, 'tipoContrato')

Null (NaN) values: 2 (0.00%)
Empty string values: 0 (0.00%)

In [19]:
df_2018.loc[df_2018["tipoContrato"].isna(), "idcontrato"]

8153     4281351
25833    4507957
Name: idcontrato, dtype: int64

In [16]:
print_top_n_list(df_2018,"tipoContrato",10)
df_2018['tipoContrato'].unique()

Top 10 most frequent values for 'tipoContrato':
tipoContrato
Aquisição de bens móveis                            60271
Aquisição de serviços                               54132
Empreitadas de obras públicas                       10341
Locação de bens móveis                               1401
Aquisição de bens móveis\nAquisição de serviços      1030
Aquisição de serviços\nLocação de bens móveis         197
Outros                                                120
Concessão de serviços públicos                         80
Concessão de obras públicas                            61
Aquisição de bens móveis\nLocação de bens móveis       43
Name: count, dtype: int64

array(['Aquisição de serviços', 'Empreitadas de obras públicas',
       'Aquisição de bens móveis', 'Locação de bens móveis',
       'Aquisição de bens móveis\nAquisição de serviços', 'Outros',
       'Aquisição de serviços\nLocação de bens móveis',
       'Aquisição de serviços\nSociedade',
       'Concessão de serviços públicos',
       'Aquisição de bens móveis\nLocação de bens móveis',
       'Concessão de obras públicas',
       'Aquisição de bens móveis\nEmpreitadas de obras públicas',
       'Aquisição de bens móveis\nSociedade', nan,
       'Aquisição de serviços\nConcessão de serviços públicos',
       'Aquisição de serviços\nEmpreitadas de obras públicas',
       'Aquisição de bens móveis\nLocação de bens móveis\nSociedade',
       'Empreitadas de obras públicas\nSociedade',
       'Aquisição de bens móveis\nConcessão de obras públicas',
       'Aquisição de bens móveis\nConcessão de serviços públicos',
       'Concessão de obras públicas\nConcessão de serviços públicos',
       'Empreitadas de obras públicas\nLocação de bens móveis',
       'Locação de bens móveis\nSociedade',
       'Aquisição de bens móveis\nConcessão de serviços públicos\nLocação de bens móveis',
       'Aquisição de serviços\nConcessão de obras públicas',
       'Aquisição de bens móveis\nOutros',
       'Concessão de obras públicas\nEmpreitadas de obras públicas',
       'Concessão de serviços públicos\nEmpreitadas de obras públicas',
       'Aquisição de serviços\nOutros',
       'Aquisição de bens móveis\nEmpreitadas de obras públicas\nSociedade',
       'Aquisição de bens móveis\nAquisição de serviços\nOutros',
       'Empreitadas de obras públicas\nOutros',
       'Aquisição de serviços\nConcessão de serviços públicos\nLocação de bens móveis',
       'Aquisição de bens móveis\nAquisição de serviços\nConcessão de serviços públicos',
       'Aquisição de serviços\nLocação de bens móveis\nSociedade'],
      dtype=object)

#### idProcedimento (int64)

In [20]:
count_null_and_empty(df_2018, 'idprocedimento')

Null (NaN) values: 0 (0.00%)
Empty string values: 0 (0.00%)

In [ ]:
print_top_n(df_2018,"idprocedimento",10)

Top 10 most frequent values for 'idprocedimento':
idprocedimento
3999765    70
3248311    62
3709129    46
4260663    42
3254083    40
3617815    35
4245026    32
3451125    30
3513953    30
3135383    29
Name: count, dtype: int64

Empty DataFrame
Columns: [idcontrato, nAnuncio, TipoAnuncio, idINCM, tipoContrato, idprocedimento, tipoprocedimento, objectoContrato, descContrato, adjudicante, adjudicatarios, dataPublicacao, dataCelebracaoContrato, precoContratual, CPV, prazoExecucao, LocalExecucao, fundamentacao, ProcedimentoCentralizado, numAcordoQuadro, DescrAcordoQuadro, precoBaseProcedimento, dataDecisaoAdjudicacao, dataFechoContrato, PrecoTotalEfetivo, regime, justifNReducEscrContrato, tipoFimContrato, CritMateriais, concorrentes, linkPecasProc, Observacoes, ContratEcologico, fundamentAjusteDireto, Ano]
Index: []

[0 rows x 35 columns]

#### tipoprocedimento

In [21]:
count_null_and_empty(df_2018, 'tipoprocedimento')

Null (NaN) values: 0 (0.00%)
Empty string values: 0 (0.00%)

In [ ]:
print_top_n(df_2018,"tipoprocedimento",10)  #8

Top 10 most frequent values for 'tipoprocedimento':
tipoprocedimento
Ajuste Direto Regime Geral                   71673
Consulta Prévia                              27913
Ao abrigo de acordo-quadro (art.º 259.º)     13418
Concurso público                             12745
Ao abrigo de acordo-quadro (art.º 258.º)      1851
Concurso limitado por prévia qualificação      272
Ajuste direto simplificado                      14
Procedimento de negociação                       1
Name: count, dtype: int64

#### objectoContrato

In [23]:
count_null_and_empty(df_2018, 'objectoContrato')

Null (NaN) values: 0 (0.00%)
Empty string values: 0 (0.00%)

In [24]:
print_top_n(df_2018,"objectoContrato",20)

Top 20 most frequent values for 'objectoContrato':
objectoContrato
MEDICAMENTOS                                                                                                                      721
REAGENTES                                                                                                                         197
MEDICAMENTOS                                                                                                                      151
MEDICAMENTOS CAPS                                                                                                                 124
Serviços técnicos especializados na área do desporto                                                                               78
O presente procedimento tem por objeto a aquisição dos bens acima identificados, para o CHPVVC,E.P.E.                              76
Prestação de serviços na área de actividade da recolha de resíduos sólidos da cidade.                                              69
PA02_2018_AQELE15                                                                                                                  68
SP 384/2018 - MEDICAMENTOS ANTI-INFECIOSOS: EXCETO ANTIVÍRICOS E ANTIFUNGÍCOS, PARA O CHTMAD, EPE                                  60
Aquisição de reagentes                                                                                                             54
MEDICAMENTOS CAPS                                                                                                                  53
Aquisição de serviços médicos sem especialidade para a ARSLVT, IP                                                                  53
Aquisição de diverso material clinico urgente                                                                                      53
Aquisição de equipamento informático                                                                                               52
Aquisição urgente de diverso material de consumo clinico                                                                           51
FORNECIMENTO DE MATERIAL DE OSTEOSSINTESE                                                                                          50
Prestação de serviços de assistência técnica                                                                                       50
Diversos Medicamentos                                                                                                              49
Medicamentos com CHNM                                                                                                              46
CONTRATAÇAO DE COLABORADORES, EM REGIME DE AVENÇA, PARA PRESTAÇÃO DE SERVIÇOS NOS COMPLEXOS MUNICIPAIS, PARA A EPOCA 2018/2019     44
Name: count, dtype: int64

#### descContrato (object)

In [25]:
count_null_and_empty(df_2018, 'descContrato')

Null (NaN) values: 8 (0.01%)
Empty string values: 0 (0.00%)

In [26]:
print_top_n(df_2018,"descContrato",20)

Top 20 most frequent values for 'descContrato':
descContrato
MEDICAMENTOS                                                                                         700
REAGENTES                                                                                            188
Contrato de Aquisição de Serviços                                                                    162
MEDICAMENTOS                                                                                         147
Contrato de prestação de serviços                                                                    121
Ajuste direto                                                                                        110
Aquisição de serviços                                                                                106
MEDICAMENTOS CAPS                                                                                    104
Contrato de aquisição de serviços                                                                     92
Contrato de Prestação de Serviços                                                                     88
MEDICAMENTOS CAPS                                                                                     71
Prestação de serviços na área de actividade da recolha de resíduos sólidos da cidade.                 69
PA02_2018_AQELE15                                                                                     69
Contrato de avença                                                                                    66
SP 384/2018 - MEDICAMENTOS ANTI-INFECIOSOS: EXCETO ANTIVÍRICOS E ANTIFUNGÍCOS, PARA O CHTMAD, EPE     61
2018-01-01 00:00:00                                                                                   60
Aquisição de diverso material clinico urgente                                                         53
Aquisição de reagentes                                                                                53
Aquisição urgente de diverso material de consumo clinico                                              51
2018-02-01 00:00:00                                                                                   50
Name: count, dtype: int64

adjudicante (object)

In [27]:
count_null_and_empty(df_2018, 'adjudicante')

Null (NaN) values: 0 (0.00%)
Empty string values: 0 (0.00%)

In [28]:
print_top_n(df_2018,"adjudicante",20)

Top 20 most frequent values for 'adjudicante':
adjudicante
508094461 - Unidade Local de Saúde do Norte Alentejano, E. P. E.                                                4197
600012662 - Ministério da Defesa Nacional - Marinha                                                             2047
508481287 - Centro Hospitalar Lisboa Norte, E. P. E.                                                            1998
509822932 - Centro Hospitalar de Leiria, E. P. E.                                                               1656
510103448 - Centro Hospitalar e Universitário de Coimbra, E. P. E.                                              1617
508481287 - Centro Hospitalar Universitário de Lisboa Norte, E. P. E.                                           1523
500051070 - Município de Lisboa                                                                                 1436
511228848 - Serviço de Saúde da Região Autónoma da Madeira, E. P. E.                                            1403
509186998 - Centro Hospitalar Barreiro Montijo, E. P. E.                                                        1376
509906478 - Centro de Formação Profissional da Indústria Têxtil, Vestuário, Confecção e Lanifícios (Modatex)    1347
501442600 - Instituto do Emprego e da Formação Profissional, I. P.                                              1239
506361470 - Hospital Garcia de Orta, E. P. E.                                                                   1178
510745997 - Centro Hospitalar Universitário do Algarve, E. P. E.                                                1108
506362299 - Instituto Português de Oncologia do Porto Francisco Gentil, E. P. E.                                1078
508142156 - Centro Hospitalar Vila Nova de Gaia - Espinho, E. P. E.                                              897
508338476 - Centro Hospitalar Psiquiátrico de Lisboa                                                             767
503148776 - Administração Regional de Saúde de Lisboa e Vale do Tejo, I. P.                                      726
500745471 - Santa Casa da Misericórdia de Lisboa                                                                 695
502098139 - Município de Loulé                                                                                   692
503135593 - Administração Regional de Saúde do Norte, I. P.                                                      667
Name: count, dtype: int64

adjudicatarios (object)

In [29]:
count_null_and_empty(df_2018, 'adjudicatarios')

Null (NaN) values: 133 (0.10%)
Empty string values: 0 (0.00%)

In [ ]:
print(df_2018['adjudicatarios'].head(20))

0                                                - - Jaime Jorge Rocha Rodrigues
1                     508472830 - Kedrion Portugal - Dist. Prod.Farm., Unip. Lda
2                                                   505792362 - Overpharma, Lda.
3                            502376899 - P.M.H. - PROD. MÉDICO-HOSPITALARES, LDA
4                                        501895558 - H.R. PRODUTOS QUIMICOS, LDA
5                                       500684324 - Medicinália - Cormédica, Lda
6         505001764 - Electro Requetim – Distribuição de Material Eléctrico, S.A
7                                     508080975 - Ricoh Portugal Unipessoal, Lda
8                                                   503047201 - CSL Behring, Lda
9                                              502041285 - GRIFOLS PORTUGAL, LDA
10                                                        502820780 - OCTAPHARMA
11                                                            500203130 - NORMAX
12                                                     508592909 - DOCWORLD, Lda
13                                            504193279 - PRICEWATERHOUSECOOPERS
14                      502480840 - Teletejo, Telecomunicações do Ribatejo, S.A.
15    503365998 - CT Q- Projectos de Engenharia e Gestão de Empreendimentos, Lda
16                                         506229580 - Olímpia &amp; Filhos, Lda
17                              502801204 - TAKEDA - Produtos Farmacêuticos, Lda
18                503413410 - COVIDIEN PORTUGAL-Produtos de Saúde,Unipessoal,Lda
19                                504282921 - Roche Sistemas de Diagnóstico, Lda
Name: adjudicatarios, dtype: str

dataPublicacao (object)

In [30]:
count_null_and_empty(df_2018, 'dataPublicacao')

Null (NaN) values: 0 (0.00%)
Empty string values: 0 (0.00%)

In [31]:
print(df_2018['dataPublicacao'].head(10))

0   2017-06-29
1   2017-11-13
2   2017-11-16
3   2017-12-21
4   2018-01-02
5   2018-01-02
6   2018-01-02
7   2018-01-02
8   2018-01-02
9   2018-01-02
Name: dataPublicacao, dtype: datetime64[ns]

dataCelebracaoContrato (object)

In [32]:
count_null_and_empty(df_2018, 'dataCelebracaoContrato')

Null (NaN) values: 14 (0.01%)
Empty string values: 0 (0.00%)

In [33]:
print(df_2018['dataCelebracaoContrato'].head(10))

0   2018-08-20
1   2018-01-31
2   2018-02-12
3   2018-04-01
4   2018-01-01
5   2018-01-01
6   2018-01-01
7   2018-01-02
8   2018-01-02
9   2018-01-02
Name: dataCelebracaoContrato, dtype: datetime64[ns]

precoContratual (float64)

In [34]:
count_null_and_empty(df_2018, 'precoContratual')

Null (NaN) values: 0 (0.00%)
Empty string values: 0 (0.00%)

In [35]:
print(df_2018['precoContratual'].head(10))

0       8800.00
1     517007.38
2      46287.62
3       3671.98
4       5000.00
5      74539.68
6    1636638.10
7       4801.68
8       8400.00
9       1247.16
Name: precoContratual, dtype: float64

cpv (object)

In [36]:
count_null_and_empty(df_2018, 'CPV')

Null (NaN) values: 1 (0.00%)
Empty string values: 0 (0.00%)

In [38]:
print(df_2018['CPV'].head(10))

0           79212500-8 - Serviços de revisão de contas
1                   45233128-2 - Construção de rotunda
2            45221119-9 - Obras de renovação de pontes
3        85147000-1 - Serviços de medicina do trabalho
4          33696000-5 - Reagentes e meios de contraste
5                   79710000-4 - Serviços de segurança
6    65300000-6 - Serviços de distribuição de elect...
7    50312310-1 - Manutenção de equipamento para re...
8    72210000-0 - Serviços de programação de pacote...
9    64210000-1 - Serviços telefónicos e de transmi...
Name: CPV, dtype: object

prazoExecucao (int64)

In [39]:
count_null_and_empty(df_2018, 'prazoExecucao')

Null (NaN) values: 0 (0.00%)
Empty string values: 0 (0.00%)

In [40]:
print_top_n(df_2018, 'prazoExecucao', 10)

Top 10 most frequent values for 'prazoExecucao':
prazoExecucao
365     22752
30      11196
1        7317
60       5081
20       4809
1095     4513
90       4507
180      3620
15       3431
10       2786
Name: count, dtype: int64

In [41]:
print_bottom_n(df_2018,'prazoExecucao',10)

Bottom 10 least frequent values for 'prazoExecucao':
prazoExecucao
474     1
1017    1
1257    1
745     1
907     1
1292    1
1284    1
1053    1
1326    1
443     1
Name: count, dtype: int64

In [42]:
max_prazo_valor = df_2018['prazoExecucao'].max()
print("Maximum 'prazoExecucao (dias)':", max_prazo_valor)
print("Maximum 'prazoExecucao (anos)':", max_prazo_valor/365)
#impossível

Maximum 'prazoExecucao (dias)': 120261324
Maximum 'prazoExecucao (anos)': 329483.0794520548

localExecucao (object)

In [43]:
count_null_and_empty(df_2018, 'LocalExecucao')

Null (NaN) values: 235 (0.18%)
Empty string values: 0 (0.00%)

In [44]:
print(df_2018['LocalExecucao'].head(10))

0                           Portugal, Coimbra, Arganil
1                       Portugal, Portugal Continental
2                       Portugal, Portugal Continental
3                             Portugal, Lisboa, Lisboa
4                   Portugal, Porto, Vila Nova de Gaia
5                            Portugal, Lisboa, Amadora
6    Portugal, Viana do Castelo, Caminha\nPortugal,...
7                             Portugal, Lisboa, Lisboa
8                             Portugal, Lisboa, Lisboa
9                             Portugal, Lisboa, Lisboa
Name: LocalExecucao, dtype: object

fundamentacao (object)

In [45]:
count_null_and_empty(df_2018, 'fundamentacao')

Null (NaN) values: 16 (0.01%)
Empty string values: 0 (0.00%)

In [46]:
print_top_n(df_2018, 'fundamentacao', 10)

Top 10 most frequent values for 'fundamentacao':
fundamentacao
Artigo 20.º, n.º 1, alínea d) do Código dos Contratos Públicos                    27504
Artigo 20.º, n.º 1, alínea c) do Código dos Contratos Públicos                    21838
Artigo 20.º, n.º 1, alínea a) do Código dos Contratos Públicos                    15276
Artigo 259.º do Código dos Contratos Públicos                                     13059
Artigo 20.º, n.º 1, alínea b) do Código dos Contratos Públicos                     7670
Artigo 24.º, n.º 1, alínea c) do Código dos Contratos Públicos                     5936
Artigo 24.º, n.º 1, alínea e), subalínea ii) do Código dos Contratos Públicos      5692
Artigo 19.º, alínea c) do Código dos Contratos Públicos                            3620
Artigo 24.º, n.º 1, alínea e), subalínea iii) do Código dos Contratos Públicos     3072
Artigo 24.º, n.º 1, alínea e) do Código dos Contratos Públicos                     2387
Name: count, dtype: int64

ProcedimentoCentralizado (object)

In [47]:
count_null_and_empty(df_2018, 'ProcedimentoCentralizado')

Null (NaN) values: 0 (0.00%)
Empty string values: 0 (0.00%)

In [48]:
print_top_n(df_2018, 'ProcedimentoCentralizado', 10)

Top 10 most frequent values for 'ProcedimentoCentralizado':
ProcedimentoCentralizado
Não    125445
Sim      2442
Name: count, dtype: int64

DescrAcordoQuadro (object)

In [49]:
count_null_and_empty(df_2018, 'DescrAcordoQuadro')

Null (NaN) values: 112788 (88.19%)
Empty string values: 0 (0.00%)

In [50]:
print_top_n(df_2018,"DescrAcordoQuadro",10)

Top 10 most frequent values for 'DescrAcordoQuadro':
DescrAcordoQuadro
CP 2015/6 - Acordo quadro para o fornecimento de Medicamentos do Foro Oncológico                                                                                                                                                                                   1197
CP 2017/6 - Acordo Quadro para fornecimento de Medicamentos do Foro Oncológico e Imunomoduladores, às Instituições e Serviços do Serviço Nacional de Saúde                                                                                                          830
Acordo quadro de licenciamento de software e serviços conexos                                                                                                                                                                                                       671
CP 2017/2 - Acordo Quadro para fornecimento de Medicamentos do Sistema Nervoso Cerebrospinal, exceto: anestésicos, relaxantes musculares, analgésicos, antipiréticos, antidepressivos e antipsicóticos  às Instituições e Serviços do Serviço Nacional de Saúde     502
CP 2017/5 - Acordo Quadro para fornecimento de Medicamentos anti-infeciosos: exceto antivíricos e antifúngicos                                                                                                                                                      466
CP 2016/01 - Acordo Quadro para fornecimento de Medicamentos do Aparelho Cardiovascular_x000D_  às Instituições e Serviços do Serviço Nacional de Saúde                                                                                                             440
Acordo Quadro para aquisição e aluguer operacional de equipamento informático                                                                                                                                                                                       385
CP 2016/18 - Acordo quadro para fornecimento de Medicamentos do Grupo 4: Sangue às Instituições e Serviços do Serviço Nacional de Saúde                                                                                                                             337
CP 2017/3 - Acordo Quadro para fornecimento de corretivos da volémia e outras soluções estéreis                                                                                                                                                                     330
Acordo quadro de fornecimento de papel e economato                                                                                                                                                                                                                  326
Name: count, dtype: int64

precoBaseProcedimento (float64)

In [51]:
count_null_and_empty(df_2018, 'precoBaseProcedimento')

Null (NaN) values: 0 (0.00%)
Empty string values: 0 (0.00%)

In [52]:
print_top_n(df_2018,"precoBaseProcedimento",10)

Top 10 most frequent values for 'precoBaseProcedimento':
precoBaseProcedimento
0.0        5111
15000.0    1017
10000.0     978
12000.0     781
20000.0     780
9000.0      674
18000.0     665
6000.0      651
30000.0     646
8000.0      549
Name: count, dtype: int64

dataDecisaoAdjudicacao (object)

In [53]:
count_null_and_empty(df_2018, 'dataDecisaoAdjudicacao')

Null (NaN) values: 2866 (2.24%)
Empty string values: 0 (0.00%)

In [54]:
print_top_n(df_2018,"dataDecisaoAdjudicacao",20)

Top 20 most frequent values for 'dataDecisaoAdjudicacao':
dataDecisaoAdjudicacao
2018-01-02    826
2018-07-26    769
2018-02-22    761
2018-01-31    748
2018-01-03    734
2018-01-10    720
2018-01-18    672
2018-01-08    670
2018-06-28    657
2018-11-29    656
2018-05-17    652
2018-07-12    649
2018-01-17    640
2018-01-12    636
2018-12-14    627
2018-01-25    627
2017-12-28    625
2018-06-27    620
2018-10-04    620
2018-02-07    619
Name: count, dtype: int64

dataFechoContrato (object)

In [55]:
count_null_and_empty(df_2018, 'dataFechoContrato')

Null (NaN) values: 78209 (61.15%)
Empty string values: 0 (0.00%)

In [56]:
print_top_n(df_2018,"dataFechoContrato",10)

Top 10 most frequent values for 'dataFechoContrato':
dataFechoContrato
2018-12-31    6709
2019-12-31    1203
2018-12-28    1040
2018-12-27     491
2018-12-21     491
2018-12-19     472
2018-12-18     402
2018-12-20     386
2018-11-30     364
2018-12-26     356
Name: count, dtype: int64

PrecoTotalEfetivo

In [57]:
count_null_and_empty(df_2018, 'PrecoTotalEfetivo')

Null (NaN) values: 0 (0.00%)
Empty string values: 0 (0.00%)

In [58]:
print(df_2018['PrecoTotalEfetivo'].head(10))

0          0.0
1          0.0
2          0.0
3          0.0
4          0.0
5          0.0
6    1594502.6
7          0.0
8          0.0
9          0.0
Name: PrecoTotalEfetivo, dtype: float64

In [59]:
print_top_n(df_2018,"PrecoTotalEfetivo",10)

Top 10 most frequent values for 'PrecoTotalEfetivo':
PrecoTotalEfetivo
0.0        76753
6000.0       189
7500.0       171
10000.0      171
15000.0      171
18000.0      152
500.0        145
12000.0      145
9000.0       140
1000.0       138
Name: count, dtype: int64

In [60]:
print_bottom_n(df_2018,"PrecoTotalEfetivo",10)

Bottom 10 least frequent values for 'PrecoTotalEfetivo':
PrecoTotalEfetivo
3852.11      1
74932.07     1
9070.00      1
39368.92     1
1892.37      1
71330.00     1
22877.83     1
88401.41     1
348812.16    1
75670.86     1
Name: count, dtype: int64

regime (object)

In [61]:
count_null_and_empty(df_2018, 'regime')

Null (NaN) values: 9 (0.01%)
Empty string values: 0 (0.00%)

In [62]:
print(df_2018['regime'].head(10))

0    Código dos Contratos Públicos (DL 18/2008)
1    Código dos Contratos Públicos (DL 18/2008)
2    Código dos Contratos Públicos (DL 18/2008)
3    Código dos Contratos Públicos (DL 18/2008)
4    Código dos Contratos Públicos (DL 18/2008)
5    Código dos Contratos Públicos (DL 18/2008)
6    Código dos Contratos Públicos (DL 18/2008)
7    Código dos Contratos Públicos (DL 18/2008)
8    Código dos Contratos Públicos (DL 18/2008)
9    Código dos Contratos Públicos (DL 18/2008)
Name: regime, dtype: object

tipoFimContrato (object)

In [63]:
count_null_and_empty(df_2018, 'tipoFimContrato')

Null (NaN) values: 76173 (59.56%)
Empty string values: 0 (0.00%)

In [64]:
print_top_n(df_2018, 'tipoFimContrato', 10)

Top 10 most frequent values for 'tipoFimContrato':
tipoFimContrato
O cumprimento, a impossibilidade definitiva e todas as restantes causas de extinção das obrigações reconhecidas pelo direito civil    50128
Resolução do Contrato                                                                                                                  1230
Revogação do Contrato                                                                                                                   321
Anulado ou Declarado Nulo                                                                                                                30
Contrato Anulado, Declarado Nulo ou Objecto de Recusa de Visto                                                                            4
Objeto de recusa de visto do Tribunal de Contas                                                                                           1
Name: count, dtype: int64

CritMateriais (object)

In [65]:
count_null_and_empty(df_2018, 'CritMateriais')

Null (NaN) values: 0 (0.00%)
Empty string values: 0 (0.00%)

In [66]:
print(df_2018['CritMateriais'].head(10))

0    Não
1    Não
2    Não
3    Não
4    Não
5    Não
6    Não
7    Não
8    Não
9    Não
Name: CritMateriais, dtype: object

In [67]:
print_top_n(df_2018,"CritMateriais",20)

Top 20 most frequent values for 'CritMateriais':
CritMateriais
Não    109587
Sim     18300
Name: count, dtype: int64

concorrentes (object)

In [68]:
count_null_and_empty(df_2018, 'concorrentes')

Null (NaN) values: 96293 (75.30%)
Empty string values: 0 (0.00%)

In [69]:
print(df_2018['concorrentes'].tail(10))

127877    505616297-Construções Jaime Mendo - Sociedade ...
127878    502286970-LEXVIPES - Sociedade de Produtos Ali...
127879                                                  NaN
127880                                                  NaN
127881                                                  NaN
127882                                                  NaN
127883    502332905-2045-EMPRESA DE SEGURANÇA\n510784399...
127884            513169946-13 YACHT BROKER, UNIPESSOAL LDA
127885                                                  NaN
127886                                                  NaN
Name: concorrentes, dtype: object

linkPecasProc (object)

In [70]:
count_null_and_empty(df_2018, 'linkPecasProc')

Null (NaN) values: 127650 (99.81%)
Empty string values: 0 (0.00%)

Observacoes (object)

In [71]:
count_null_and_empty(df_2018, 'Observacoes')

Null (NaN) values: 114009 (89.15%)
Empty string values: 556 (0.43%)

ContratEcologico (object)

In [72]:
count_null_and_empty(df_2018, 'ContratEcologico')

Null (NaN) values: 0 (0.00%)
Empty string values: 0 (0.00%)

Ano (int64)

In [73]:
count_null_and_empty(df_2018, 'Ano')

Null (NaN) values: 0 (0.00%)
Empty string values: 0 (0.00%)

In [74]:
print(df_2018['Ano'].head(10))

0    2018
1    2018
2    2018
3    2018
4    2018
5    2018
6    2018
7    2018
8    2018
9    2018
Name: Ano, dtype: int64

fundamentAjusteDireto (object)

In [75]:
count_null_and_empty(df_2018, 'fundamentAjusteDireto')

Null (NaN) values: 77064 (60.26%)
Empty string values: 0 (0.00%)

In [ ]:
print_top_n(df_2018,'fundamentAjusteDireto',2)

Top 2 most frequent values for 'fundamentAjusteDireto':
fundamentAjusteDireto
ausência de recursos próprios    44737
outros                            1638
Name: count, dtype: int64

Informação geral

In [76]:
df_2018.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127887 entries, 0 to 127886
Data columns (total 35 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   idcontrato                127887 non-null  int64
 1   nAnuncio                  12580 non-null   object
 2   TipoAnuncio               12580 non-null   object
 3   idINCM                    12580 non-null   float64
 4   tipoContrato              127885 non-null  object
 5   idprocedimento            127887 non-null  int64
 6   tipoprocedimento          127887 non-null  object
 7   objectoContrato           127887 non-null  object
 8   descContrato              127879 non-null  object
 9   adjudicante               127887 non-null  object
 10  adjudicatarios            127754 non-null  object
 11  dataPublicacao            127887 non-null  datetime64[ns]
 12  dataCelebracaoContrato    127873 non-null  datetime64[ns]
 13  precoContratual           127887 non-null  float64
 14  CPV                       127886 non-null  object
 15  prazoExecucao             127887 non-null  int64
 16  LocalExecucao             127652 non-null  object
 17  fundamentacao             127871 non-null  object
 18  ProcedimentoCentralizado  127887 non-null  object
 19  numAcordoQuadro           15099 non-null   float64
 20  DescrAcordoQuadro         15099 non-null   object
 21  precoBaseProcedimento     127887 non-null  float64
 22  dataDecisaoAdjudicacao    125021 non-null  datetime64[ns]
 23  dataFechoContrato         49678 non-null   datetime64[ns]
 24  PrecoTotalEfetivo         127887 non-null  float64
 25  regime                    127878 non-null  object
 26  justifNReducEscrContrato  2923 non-null    object
 27  tipoFimContrato           51714 non-null   object
 28  CritMateriais             127887 non-null  object
 29  concorrentes              31594 non-null   object
 30  linkPecasProc             237 non-null     object
 31  Observacoes               13878 non-null   object
 32  ContratEcologico          127887 non-null  object
 33  fundamentAjusteDireto     50823 non-null   object
 34  Ano                       127887 non-null  int64
dtypes: datetime64[ns](4), float64(5), int64(4), object(22)
memory usage: 34.1+ MB